title: "Bussard App dashboard"
logo: "assets/logo.png"

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3"
connectivityCheck: true

proxy:
  useCredentials: false 

defaults:
  layout: columns
  colorTheme: auto

theme: default

colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

links:
  - name: "Link 1"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank"
  - name: "link 2"
    icon: "fas fa-book"
    url: "https://github.com/bastienwirtz/homer"

services:
  - name: "Dashboards"
    icon: "fas fa-cloud"
    items:
      - name: "Kubernetes Dashboard"
        logo: "assets/tools/kubes.png"
        tag: "app"
        url: "https://dash.bussard.xyz"
        target: "_blank"
      - name: "iDRAC"
        logo: "assets/tools/idrac.png"
        tag: "app"
        url: "https://idrac.bussard.xyz"
        target: "_blank"
      - name: "Proxmox"
        logo: "assets/tools/proxmox.png"
        tag: "app"
        url: "https://zeno.bussard.xyz"
        target: "_blank"
  - name: "Services"
    icon: "fas fa-network-wired"
    items:
      - name: "Adguard"
        logo: "assets/tools/adguardhome.png"
        url: "https://adguard.bussard.xyz"
        target: "_blank"
        type: "AdguardHome"
      - name: "Vaultwarden"
        logo: "assets/tools/vaultwarden.png"
        tag: "app"
        url: "https://vault.bussard.xyz"
        target: "_blank"
      - name: "Home Assistant"
        logo: "assets/tools/as.png"
        tag: "app"
        url: "https://home.bussard.xyz"
        target: "_blank"
  - name: "Data"
    icon: "fas fa-database"
    items:
      - name: "InfluxDB"
        logo: "assets/tools/influx.png"
        tag: "app"
        url: "https://influx.bussard.xyz"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        tag: "app"
        url: "https://grafana.bussard.xyz"
        target: "_blank"